# -*- coding: utf-8 -*-
"""qwen_tts.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JOebp3hwtw8BVeosUwtRj4kpP67sBx35

# 🔊 Qwen3-TTS — Speech Synthesis Notebook

> Generate speech using **Qwen3-TTS** models (0.6B & 1.7B) with three modes:
> **Custom Voice** · **Voice Design** · **Voice Clone**
- 🎬 YouTube: [youtube.com/@marat_ai](https://www.youtube.com/@marat_ai)
- 🅿️ Patreon: [patreon.com/marat_ai](https://www.patreon.com/marat_ai)
"""

#@title ## ⚙️ Step 1 — Install Dependencies { display-mode: "form" }

#@markdown Installs `qwen-tts`, `flash-attn`, `gradio`, `soundfile`, `scipy`.
#@markdown
#@markdown Log will be cleared after installation — only a summary will remain.

import subprocess, sys, time
from IPython.display import clear_output

packages = [
    ("qwen-tts",    "qwen-tts"),
    ("flash-attn",  "flash-attn --no-build-isolation"),
    ("gradio",      "gradio"),
    ("soundfile",   "soundfile"),
    ("scipy",       "scipy"),
]

for name, cmd in packages:
    print(f"Installing {name} ...")
    subprocess.run(
        [sys.executable, "-m", "pip", "install", "-q"] + cmd.split(),
        capture_output=True, text=True,
    )

time.sleep(1)
clear_output()
print("✅ All dependencies installed successfully.")

#@title ## 📥 Step 2 — Download Models { display-mode: "form" }

#@markdown Select which models to download.
#@markdown **1.7B** models have better quality but require more VRAM.
#@markdown **0.6B** models are lighter and faster.
#@markdown
#@markdown ---
#@markdown **Model Selection:**

download_tokenizer          = True  #@param {type:"boolean"}
download_custom_voice_1_7B  = False  #@param {type:"boolean"}
download_voice_design_1_7B  = False  #@param {type:"boolean"}
download_base_1_7B          = True  #@param {type:"boolean"}
download_custom_voice_0_6B  = False #@param {type:"boolean"}
download_base_0_6B          = True #@param {type:"boolean"}

import time, os
from huggingface_hub import snapshot_download
from IPython.display import clear_output

os.makedirs("./models", exist_ok=True)

MODEL_MAP = [
    (download_tokenizer,         "Qwen/Qwen3-TTS-Tokenizer-12Hz",          "Tokenizer-12Hz"),
    (download_custom_voice_1_7B, "Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice",  "1.7B-CustomVoice"),
    (download_voice_design_1_7B, "Qwen/Qwen3-TTS-12Hz-1.7B-VoiceDesign",  "1.7B-VoiceDesign"),
    (download_base_1_7B,         "Qwen/Qwen3-TTS-12Hz-1.7B-Base",         "1.7B-Base"),
    (download_custom_voice_0_6B, "Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice",  "0.6B-CustomVoice"),
    (download_base_0_6B,         "Qwen/Qwen3-TTS-12Hz-0.6B-Base",         "0.6B-Base"),
]

results = []

for enabled, repo_id, short_name in MODEL_MAP:
    if not enabled:
        continue
    print(f"📥 Downloading {short_name} ...")
    t0 = time.time()
    try:
        local_dir = f"./models/{repo_id.split('/')[-1]}"
        snapshot_download(
            repo_id=repo_id,
            local_dir=local_dir,
            local_dir_use_symlinks=False,
            resume_download=True,
        )
        results.append(f"  ✅  {short_name}  ({time.time() - t0:.0f}s)")
    except Exception as e:
        results.append(f"  ❌  {short_name}  — {e}")

time.sleep(1)
clear_output()

print("Models download complete.\n")
for line in results:
    print(line)

#@title ## 🚀 Step 3 — Launch Gradio Interface { display-mode: "form" }

#@markdown Gradio app with **dynamic model switching**.
#@markdown
#@markdown Only **one model** is loaded into GPU at a time.
#@markdown When you switch mode or model size, the previous model is unloaded automatically.
#@markdown
#@markdown Uses **Cloudflare Tunnel** for a reliable public link.

import os, gc, subprocess, re, time, threading, socket, torch
import numpy as np
import soundfile as sf
import tempfile
import gradio as gr
from qwen_tts import Qwen3TTSModel
from IPython.display import clear_output

# ============================================
# Silent GPU / Attention check
# ============================================
if torch.cuda.is_available():
    compute_cap = torch.cuda.get_device_capability(0)
    attn_impl = "flash_attention_2" if compute_cap[0] >= 8 else "sdpa"
    DEVICE = "cuda:0"
    DTYPE = torch.float16
else:
    attn_impl = "eager"
    DEVICE = "cpu"
    DTYPE = torch.float32

# ============================================
# Model Manager — Dynamic GPU Swapping
# ============================================
class ModelManager:
    def __init__(self):
        self.current_key = None
        self.model = None

    def get(self, key):
        if self.current_key == key and self.model is not None:
            return self.model
        if self.model is not None:
            del self.model
            self.model = None
            gc.collect()
            if torch.cuda.is_available():
                torch.cuda.empty_cache()
        local = f"./models/Qwen3-TTS-12Hz-{key}"
        if not os.path.isdir(local):
            raise FileNotFoundError(f"Model not found at {local}. Please run Step 2 first.")
        self.model = Qwen3TTSModel.from_pretrained(
            local, device_map=DEVICE, dtype=DTYPE, attn_implementation=attn_impl,
        )
        self.current_key = key
        return self.model

manager = ModelManager()

# ============================================
# Configuration
# ============================================
SPEAKERS = [
    "Vivian", "Serena", "Uncle_Fu", "Dylan", "Eric",
    "Ryan", "Aiden", "Ono_Anna", "Sohee",
]
LANGUAGES = [
    "Auto", "Chinese", "English", "Japanese", "Korean",
    "German", "French", "Russian", "Portuguese", "Spanish", "Italian",
]
SPEAKER_INFO = {
    "Vivian": "🇨🇳 Bright, slightly edgy young female voice",
    "Serena": "🇨🇳 Warm, gentle young female voice",
    "Uncle_Fu": "🇨🇳 Seasoned male voice with low, mellow timbre",
    "Dylan": "🇨🇳 Youthful Beijing male voice, clear and natural",
    "Eric": "🇨🇳 Lively Sichuan male voice, slightly husky",
    "Ryan": "🇺🇸 Dynamic male voice with strong rhythmic drive",
    "Aiden": "🇺🇸 Sunny American male voice, clear midrange",
    "Ono_Anna": "🇯🇵 Playful Japanese female voice, light and nimble",
    "Sohee": "🇰🇷 Warm Korean female voice with rich emotion",
}
MODEL_SIZES = ["1.7B", "0.6B"]

# ============================================
# Generation Functions
# ============================================
def generate_custom_voice(text, language, speaker, instruct, model_size, progress=gr.Progress()):
    if not text.strip():
        raise gr.Error("Please enter some text!")
    progress(0.1, desc=f"Loading {model_size}-CustomVoice ...")
    model = manager.get(f"{model_size}-CustomVoice")
    progress(0.3, desc="Generating speech...")
    kwargs = dict(text=text, language=language if language != "Auto" else "Auto", speaker=speaker)
    if instruct and instruct.strip():
        kwargs["instruct"] = instruct.strip()
    wavs, sr = model.generate_custom_voice(**kwargs)
    progress(0.9, desc="Saving audio...")
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        sf.write(f.name, wavs[0], sr)
        return f.name

def generate_voice_design(text, language, instruct, progress=gr.Progress()):
    if not text.strip():
        raise gr.Error("Please enter some text!")
    if not instruct.strip():
        raise gr.Error("Please enter a voice description!")
    progress(0.1, desc="Loading 1.7B-VoiceDesign ...")
    model = manager.get("1.7B-VoiceDesign")
    progress(0.3, desc="Designing voice & generating speech...")
    wavs, sr = model.generate_voice_design(
        text=text, language=language if language != "Auto" else "Auto", instruct=instruct,
    )
    progress(0.9, desc="Saving audio...")
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        sf.write(f.name, wavs[0], sr)
        return f.name

def generate_voice_clone(text, language, ref_audio, ref_text, model_size, progress=gr.Progress()):
    if not text.strip():
        raise gr.Error("Please enter some text!")
    if ref_audio is None:
        raise gr.Error("Please upload reference audio!")
    progress(0.1, desc=f"Loading {model_size}-Base ...")
    model = manager.get(f"{model_size}-Base")
    progress(0.3, desc="Cloning voice & generating speech...")
    wavs, sr = model.generate_voice_clone(
        text=text, language=language if language != "Auto" else "Auto",
        ref_audio=ref_audio,
        ref_text=ref_text if ref_text and ref_text.strip() else None,
    )
    progress(0.9, desc="Saving audio...")
    with tempfile.NamedTemporaryFile(suffix=".wav", delete=False) as f:
        sf.write(f.name, wavs[0], sr)
        return f.name

# ============================================
# Build Gradio Interface
# ============================================
with gr.Blocks(
    title="Qwen3-TTS",
    theme="rocketpal/apple-light",
) as demo:

    gr.HTML("""
        <div style="text-align: center; padding: 20px;">
            <h1 style="font-size: 2.5em; margin-bottom: 0.2em;">🎙️ Qwen3-TTS</h1>
            <p style="color: #666; font-size: 1.1em;">
                Multilingual Text-to-Speech | 10 Languages | Dynamic Model Switching
            </p>
            <p style="color: #999; font-size: 0.9em;">
                Only one model loaded in GPU at a time — models swap automatically
            </p>
        </div>
    """)

    with gr.Tabs():

        # ── Tab 1: Custom Voice ──────────────────────────────────
        with gr.TabItem("🎤 Custom Voice"):
            gr.Markdown("**Use preset voices with optional style control**")
            with gr.Row():
                with gr.Column():
                    cv_text = gr.Textbox(label="Text", placeholder="Enter text to synthesize...", lines=3)
                    with gr.Row():
                        cv_language = gr.Dropdown(LANGUAGES, value="Auto", label="Language")
                        cv_speaker = gr.Dropdown(SPEAKERS, value="Ryan", label="Voice")
                    cv_size = gr.Radio(MODEL_SIZES, value="1.7B", label="Model Size",
                                       info="1.7B = better quality + instruction control. 0.6B = faster, no instructions.")
                    cv_instruct = gr.Textbox(label="Style Instruction (optional, 1.7B only)",
                                             placeholder="e.g., Happy, Whisper, Sad...", lines=1)
                    cv_btn = gr.Button("🔊 Generate", variant="primary")
                with gr.Column():
                    cv_output = gr.Audio(label="Output", type="filepath")
                    with gr.Accordion("Voice Info", open=False):
                        gr.Markdown("\n".join([f"- **{k}**: {v}" for k, v in SPEAKER_INFO.items()]))
            cv_btn.click(generate_custom_voice, [cv_text, cv_language, cv_speaker, cv_instruct, cv_size], cv_output)
            gr.Examples(
                [["Hello! Welcome to Qwen3 TTS demo!", "English", "Ryan", "Friendly", "1.7B"],
                 ["今天天气真好！", "Chinese", "Vivian", "Happy", "1.7B"]],
                [cv_text, cv_language, cv_speaker, cv_instruct, cv_size],
            )

        # ── Tab 2: Voice Design ──────────────────────────────────
        with gr.TabItem("🎨 Voice Design"):
            gr.Markdown("**Create custom voices from text descriptions**\n\n*Only available as 1.7B — there is no 0.6B VoiceDesign model.*")
            with gr.Row():
                with gr.Column():
                    vd_text = gr.Textbox(label="Text", placeholder="Enter text...", lines=3)
                    vd_language = gr.Dropdown(LANGUAGES, value="English", label="Language")
                    vd_instruct = gr.Textbox(label="Voice Description",
                                             placeholder="e.g., Young female, 25yo, warm voice, speaks slowly...", lines=3)
                    vd_btn = gr.Button("🔊 Generate", variant="primary")
                with gr.Column():
                    vd_output = gr.Audio(label="Output", type="filepath")
            vd_btn.click(generate_voice_design, [vd_text, vd_language, vd_instruct], vd_output)
            gr.Examples(
                [["Welcome to our podcast!", "English", "Male, 35yo, deep voice, professional broadcaster"],
                 ["Once upon a time...", "English", "Elderly woman, warm grandma voice, storytelling"]],
                [vd_text, vd_language, vd_instruct],
            )

        # ── Tab 3: Voice Clone ───────────────────────────────────
        with gr.TabItem("🔄 Voice Clone"):
            gr.Markdown("**Clone any voice from a 3+ second audio sample**")
            with gr.Row():
                with gr.Column():
                    vc_ref_audio = gr.Audio(label="Reference Audio", type="filepath", sources=["upload", "microphone"])
                    vc_ref_text = gr.Textbox(label="Reference Transcript (Recommended)",
                                             placeholder="What is said in the audio...", lines=2)
                    vc_text = gr.Textbox(label="Text to Synthesize", placeholder="New text to speak...", lines=3)
                    vc_language = gr.Dropdown(LANGUAGES, value="Auto", label="Language")
                    vc_size = gr.Radio(MODEL_SIZES, value="1.7B", label="Model Size",
                                       info="1.7B = better clone quality. 0.6B = faster.")
                    vc_btn = gr.Button("🔊 Clone & Generate", variant="primary")
                with gr.Column():
                    vc_output = gr.Audio(label="Output", type="filepath")
                    gr.Markdown("""
                    **Tips:**
                    - Use clean audio (no background noise)
                    - 3-10 seconds is ideal
                    - Providing transcript improves quality
                    """)
            vc_btn.click(generate_voice_clone, [vc_text, vc_language, vc_ref_audio, vc_ref_text, vc_size], vc_output)

    # Footer
    gr.HTML("""
        <div style="text-align: center; padding: 20px; margin-top: 20px; border-top: 1px solid #eee;">
            <a href="https://www.youtube.com/@marat_ai" target="_blank">YouTube @marat_ai</a> •
            <a href="https://www.patreon.com/marat_ai" target="_blank">Patreon</a> •
            <a href="https://github.com/QwenLM/Qwen3-TTS" target="_blank">GitHub</a> •
            <a href="https://huggingface.co/collections/Qwen/qwen3-tts" target="_blank">HuggingFace</a> •
            <a href="https://arxiv.org/abs/2601.15621" target="_blank">Paper</a>
        </div>
    """)

# ============================================
# Install cloudflared & launch with tunnel
# ============================================
clear_output()
print("🔧 Setting up ...")

# Kill any previous processes
subprocess.run(["fuser", "-k", "-n", "tcp", "7860"], capture_output=True)
subprocess.run(["fuser", "-k", "-n", "tcp", "7861"], capture_output=True)
subprocess.run(["fuser", "-k", "-n", "tcp", "7862"], capture_output=True)
subprocess.run(["killall", "cloudflared"], capture_output=True)
time.sleep(2)

# Find a free port
def find_free_port(start=7860, end=7880):
    for port in range(start, end):
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            try:
                s.bind(("127.0.0.1", port))
                return port
            except OSError:
                continue
    raise RuntimeError("No free port found")

PORT = find_free_port()

# Install cloudflared
subprocess.run(
    ["wget", "-q", "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb"],
    capture_output=True,
)
subprocess.run(["dpkg", "-i", "cloudflared-linux-amd64.deb"], capture_output=True)

# Launch Gradio locally (non-blocking, no inline iframe)
demo.queue()
demo.launch(
    server_name="0.0.0.0",
    server_port=PORT,
    share=False,
    inline=False,
    quiet=True,
    show_error=True,
    prevent_thread_lock=True,
)

# Start cloudflared tunnel in background and capture URL
proc = subprocess.Popen(
    ["cloudflared", "tunnel", "--url", f"http://127.0.0.1:{PORT}"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE,
)

tunnel_url = None
for _ in range(30):
    time.sleep(1)
    line = proc.stderr.readline().decode("utf-8", errors="ignore")
    match = re.search(r"(https://[a-zA-Z0-9\-]+\.trycloudflare\.com)", line)
    if match:
        tunnel_url = match.group(1)
        break

clear_output()

if tunnel_url:
    print(f"✅ Public link: {tunnel_url}")
else:
    print(f"⚠️ Cloudflare tunnel failed. Local link: http://127.0.0.1:{PORT}")
    print("   Try re-running this cell.")