# -*- coding: utf-8 -*-
"""Qwen TTS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfOL630Qvffbpvf0R460oyst0O9NAgPT
"""

!pip install -q "transformers" "accelerate" "soundfile"
!pip install -q qwen-tts

# https://mjunya.com/flash-attention-prebuild-wheels/
!pip install https://github.com/mjun0812/flash-attention-prebuild-wheels/releases/download/v0.9.0/flash_attn-2.8.3+cu128torch2.10-cp312-cp312-linux_x86_64.whl
!apt-get -y install sox libsox-fmt-all

# Commented out IPython magic to ensure Python compatibility.
# %%writefile setup_QwenTTS.py
# import torch
# import soundfile as sf
# import os
# import gc
# import numpy as np
# from IPython.display import display, Audio
# from qwen_tts import Qwen3TTSModel
# 
# # Khởi tạo mô hình
# model = Qwen3TTSModel.from_pretrained(
#     "Qwen/Qwen3-TTS-12Hz-1.7B-Base",
#     device_map="cuda:0",
#     dtype=torch.bfloat16,
#     attn_implementation="flash_attention_2", # Bạn đã cài thành công nên tự tin dùng
# )
# 
# # Định nghĩa tham số giọng đọc tự nhiên (Lấy từ common_gen_kwargs)
# gen_kwargs = {
#     "max_new_tokens": 2048, "do_sample": True, "top_k": 50, "top_p": 1.0,
#     "temperature": 0.9, "repetition_penalty": 1.05,
#     "subtalker_dosample": True, "subtalker_top_k": 50,
#     "subtalker_top_p": 1.0, "subtalker_temperature": 0.9,
# }
# 
# # Thông tin file mẫu (Sửa thành file của bạn)
# ref_audio_path = "/content/Minimax - Nature Show Host.mp3"
# ref_text = "Hello. I'm delighted to assist you with our voice services. Choose a voice that resonates with you, and let's begin our creative audio journey together."
# 
# # Đọc file text
# input_file = "raw_en.txt"
# output_dir = "output_audio"
# 
# # MÃ HÓA GIỌNG MẪU 1 LẦN DUY NHẤT (TRƯỚC VÒNG LẶP)
# print("Đang trích xuất đặc trưng giọng mẫu...")
# voice_prompt = model.create_voice_clone_prompt(
#     ref_audio=ref_audio_path,
#     ref_text=ref_text,
#     x_vector_only_mode=False
# )
# 
# # Khởi tạo một mảng rỗng để chứa toàn bộ dữ liệu âm thanh trước khi vào vòng lặp
# all_audio_segments = []
# 
# os.makedirs(output_dir, exist_ok=True)
# 
# with open(input_file, "r", encoding="utf-8") as f:
#     # Lọc bỏ các dòng trống
#     lines = [line.strip() for line in f.readlines() if line.strip()]
# 
# # 3. Cấu hình Kích thước Lô (Batch Size)
# # NẾU DÙNG T4 (16GB VRAM): Nên để 2 hoặc 4 để tránh tràn RAM
# # NẾU DÙNG A100/L4: Có thể tăng lên 8 hoặc 16
# BATCH_SIZE = 32
# 
# print(f"Bắt đầu xử lý {len(lines)} dòng, mỗi lần xử lý {BATCH_SIZE} dòng song song...")
# 
# # 4. Vòng lặp xử lý theo lô
# for i in range(0, len(lines), BATCH_SIZE):
#     # Cắt ra một lô (batch) text
#     batch_texts = lines[i : i + BATCH_SIZE]
# 
#     # Qwen3 yêu cầu khai báo ngôn ngữ cho TỪNG text trong lô
#     batch_langs = ["Auto"] * len(batch_texts)
# 
#     print(f"Đang xử lý lô từ dòng {i+1} đến {i + len(batch_texts)}...")
# 
#     # Gọi mô hình 1 lần duy nhất cho nhiều dòng text
#     with torch.no_grad():
#         wav_outputs, sr = model.generate_voice_clone(
#             text=batch_texts,       # Truyền mảng List thay vì String đơn
#             language=batch_langs,   # Truyền mảng List
#             ref_audio=ref_audio_path,
#             ref_text=ref_text,
#             x_vector_only_mode=False,
#             **gen_kwargs
#         )
# 
#     # 5. Lưu kết quả từng dòng và lưu trữ dữ liệu để ghép
#     for j, wav_data in enumerate(wav_outputs):
#         line_index = i + j + 1
#         file_name = os.path.join(output_dir, f"audio_dong_{line_index}.wav")
# 
#         # 1. ĐẢM BẢO CHẮC CHẮN dữ liệu nằm ở CPU, không nằm ở GPU
#         if isinstance(wav_data, torch.Tensor):
#             wav_data_safe = wav_data.detach().cpu().numpy()
#         else:
#             # Nếu nó đã là numpy array, copy ra vùng nhớ mới để cắt đứt liên kết
#             wav_data_safe = np.copy(wav_data)
#         sf.write(file_name, wav_data_safe, sr)
# 
#         # Thêm đoạn âm thanh hiện tại vào danh sách tổng
#         all_audio_segments.append(wav_data_safe)
# 
#         # Tạo thêm 0.1 giây khoảng lặng (silence) để câu văn có nhịp ngắt nghỉ tự nhiên
#         silence_gap = np.zeros(int(0.1 * sr), dtype=wav_data_safe.dtype)
#         all_audio_segments.append(silence_gap)
# 
#     # 6. DỌN DẸP VRAM (Cực kỳ quan trọng để không sập Colab giữa chừng)
#     del wav_outputs
#     gc.collect()
#     torch.cuda.empty_cache()
# 
# # ==========================================
# # 7. MERGE AUDIO VÀ TẠO TRÌNH PHÁT PREVIEW
# # ==========================================
# print("\nĐang tiến hành ghép các đoạn âm thanh...")
# 
# # Nối tất cả các mảng numpy nhỏ lại thành 1 mảng âm thanh dài duy nhất
# merged_audio = np.concatenate(all_audio_segments)
# 
# # Lưu file hoàn chỉnh ra ổ cứng
# merged_file_path = os.path.join(output_dir, "audio_hoan_chinh.wav")
# sf.write(merged_file_path, merged_audio, sr)
# print(f"✅ Đã lưu file ghép hoàn chỉnh tại: {merged_file_path}")
# 
# # Build giao diện Preview trực tiếp ngay trên Colab (Không cần Gradio)
# print("\n🎧 Nghe thử bản Preview toàn bộ file:")
# display(Audio(data=merged_audio, rate=sr))

!python setup_QwenTTS.py
