# -*- coding: utf-8 -*-
"""voicevox

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15eQLjVXfEi_WbSK7C9o4BttVhS6Wcm6V
"""

!pip install aiohttp -q

import os
import wave
import io
import asyncio
import aiohttp
from IPython.display import Audio, display

base_url = "http://127.0.0.1:50021"

# 1. ĐỔI ID NHÂN VẬT
speaker_id = 100

# 2. ĐỔI ��ƯỜNG DẪN VỀ BẢN ENGINE CHUẨN
output_dir = "/content/voicevox_engine/tmp"
os.makedirs(output_dir, exist_ok=True)

# Đọc file (Đảm bảo bạn đã tạo file raw.txt và ghi nội dung tiếng Nhật vào trong đó)
with open("/content/raw_ja_v1.txt", "r", encoding="utf-8") as f:
    lines = [line.strip() for line in f.readlines() if line.strip()]

# 3. CHỈNH LẠI MỨC REQUEST SONG SONG AN TOÀN CHO GPU COLAB
CONCURRENT_REQUESTS = 50 # Tối ưu nhất cho GPU T4, để 100 sẽ bị sập Server do tràn RAM
MAX_RETRIES = 3 # Số lần thử lại tối đa
semaphore = asyncio.Semaphore(CONCURRENT_REQUESTS)

async def process_single_line(session, index, line):
    """Hàm xử lý cho 1 dòng độc lập, có cơ chế Retry khi thất bại"""
    async with semaphore:
        for attempt in range(MAX_RETRIES):
            try:
                # 1. Audio Query (Bất đồng bộ)
                async with session.post(f"{base_url}/audio_query", params={"text": line, "speaker": speaker_id}) as query_res:
                    if query_res.status != 200:
                        print(f"[{index}] ⚠️ Lỗi Query (Lần thử {attempt + 1}/{MAX_RETRIES}): {await query_res.text()}")
                        if attempt < MAX_RETRIES - 1:
                            await asyncio.sleep(1) # Nghỉ 1 giây trước khi thử lại
                            continue
                        return index, None # Hết lượt thử -> Chấp nhận thất bại

                    query_data = await query_res.json()

                # Chỉnh sửa tham số giọng nói (Bạn có thể tùy chỉnh lại ở đây)
                query_data['speedScale'] = 1
                query_data['pitchScale'] = -0.05
                query_data['intonationScale'] = 1 # Cảm xúc
                query_data['volumeScale'] = 2
                query_data["outputSamplingRate"] = 48000
                # query_data["prePhonemeLength"] = 0.5 # nhịp nghỉ đầu
                # query_data["postPhonemeLength"] = 0.5 # nhịp nghỉ cuối

                # 2. Synthesis (Bất đồng bộ)
                async with session.post(f"{base_url}/synthesis", params={"speaker": speaker_id}, json=query_data) as synth_res:
                    if synth_res.status != 200:
                        print(f"[{index}] ⚠️ Lỗi Tổng hợp (Lần thử {attempt + 1}/{MAX_RETRIES}): {await synth_res.text()}")
                        if attempt < MAX_RETRIES - 1:
                            await asyncio.sleep(1)
                            continue
                        return index, None

                    audio_content = await synth_res.read()

                # Lưu file rời
                filename = os.path.join(output_dir, f"output_part_{index}.wav")
                with open(filename, "wb") as out_f:
                    out_f.write(audio_content)

                print(f"✅ Đã xong câu {index}/{len(lines)}")
                return index, audio_content # Thành công -> Trả về kết quả và thoát vòng lặp

            except Exception as e:
                print(f"[{index}] ⚠️ Lỗi kết nối (Lần thử {attempt + 1}/{MAX_RETRIES}): {e}")
                if attempt < MAX_RETRIES - 1:
                    await asyncio.sleep(1)
                    continue
                return index, None

async def main():
    if not lines:
        print("❌ File raw.txt trống hoặc không tồn tại. Vui lòng kiểm tra lại.")
        return

    print(f"🚀 BẮT ĐẦU XỬ LÝ SONG SONG {len(lines)} CÂU VỚI {CONCURRENT_REQUESTS} LUỒNG...")

    # Tạo phiên HTTP dùng chung để tăng tốc độ kết nối
    async with aiohttp.ClientSession() as session:
        # Tạo danh sách các tác vụ (tasks)
        tasks = [process_single_line(session, i + 1, line) for i, line in enumerate(lines)]

        # Chạy TẤT CẢ các tác vụ cùng một lúc và chờ đến khi tất cả xong
        results = await asyncio.gather(*tasks)

    print("\n🔄 Đang sắp xếp và ghép nối các đoạn âm thanh...")

    # Sắp xếp lại (sort) kết quả dựa vào index để âm thanh không bị lộn xộn.
    results.sort(key=lambda x: x[0])

    audio_frames = []
    wav_params = None

    for index, audio_content in results:
        if audio_content:
            with wave.open(io.BytesIO(audio_content), 'rb') as w:
                if wav_params is None:
                    wav_params = w.getparams()
                audio_frames.append(w.readframes(w.getnframes()))

    # Xuất file cuối cùng
    if audio_frames:
        final_filename = os.path.join(output_dir, "output_final.wav")
        with wave.open(final_filename, 'wb') as w:
            w.setparams(wav_params)
            for frames in audio_frames:
                w.writeframes(frames)

        print(f"✨ HOÀN TẤT XUẤT FILE TỔNG: {final_filename}")
        display(Audio(final_filename))
    else:
        print("\n❌ Không có đoạn âm thanh nào được tạo thành công.")

# Kích hoạt chạy vòng lặp bất đồng bộ trong Colab
await main()